### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by iMaxxx** [bolt/Sitemap#12]
Installation stucking on: Generating autoload files
After reloading extensions overview page you get an error and no extensions list:
Warning: set_time_limit(): Cannot set max execution time limit due to system policy in /..../extensions/vendor/bolt/sitemap/Extension.php on line 10 

(Bolt 2.2.7)

**Comment by iMaxxx** [comment]
It work if I comment this line

**Comment by bobdenotter** [comment]
This should've been fixed in Bolt 3.0. If not, feel free to re-open.
