### ISSUE TITLE
How can i have custom the template?

### ISSUE THREAD

**Issue by everyx** [bolt/Sitemap#13]
Hi, greate extension.

I want to do some custom in the twig template, so how can I do this without modify the original file in this extension?

**Comment by GawainLynch** [comment]
In your extension configuration, you just set the `template:` setting to a relative path/filename in your theme. The magic of Twig :smiley: 

e.g. in my themes I create the directory `extensions/sitemap` and put my custom template in there as  `sitemap.twig`, then in config:

```yaml
template: extensions/sitemap/sitemap.twig
```

**Comment by everyx** [comment]
Great, and so many thanks :) :+1:
