### ISSUE TITLE
PHP in_array() errors occur when config ignore value is blank

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/Sitemap#22]
Sample config:

```
# sitemap settings

template: sitemap.twig
xml_template: sitemap_xml.twig

ignore:

## ignore by "slug" of contenttype
ignore_contenttype:
  - keyfacts
  - testimonials
```

If `ignore:` is kept like it is above, it will result in the following error currently:

`Warning: in_array() expects parameter 2 to be array, null given in /{PATH}/extensions/vendor/bolt/sitemap/src/SitemapExtension.php on line 177`

Commenting out `ignore` with `#ignore` resolves the issue.

**Comment by bobdenotter** [comment]
This has been fixed. Closing for now, feel free to re-open, if I missed something.
