### ISSUE TITLE
Sitemap doesn't see pages (contentypes) where searchable is set to false

### ISSUE THREAD

**Issue by jarek-gilewski** [bolt/Sitemap#23]
Sitemap doesn't work for contentype where searchable is set to false. When you set searchable: true page is visible in XML sitemap.  I know that this is feature but there should be a option to deactivate this behavior.

**Comment by bobdenotter** [comment]
Yes, that's the expected behaviour. 

Sitemap is to facilitate search (by Google, for instance). If something is not searchable, it should also be omitted from the sitemap.

**Comment by jarek-gilewski** [comment]
As far I understand searchable:false excludes contentype from internal bolt search - it doesn't exclude from Google search results (page with searchable:false have following meta robots <meta name="robots" content="index, follow" /> and page is visible in Google)

From bolt-cms manual:
By setting searchable: false these Contenttype records will be excluded from search results.

**Comment by jarek-gilewski** [comment]
Option has been disabled in sitemap php file (SitemapExtension.php) but it's good to move this option to config file.
