### ISSUE TITLE
The missing link

### ISSUE THREAD

**Issue by evertalbers** [bolt/Sitemap#25]
After installing Sitemap 2.0.5 on Bolt 3.2.5 I get a missing link in the confirmation box. ("...docs can be found via the following link." and then nothing). See Dutch screenshot.

![bolt_uitbreiden_ _bolt_-_2017-01-16_18 20 22 jpeg](https://cloud.githubusercontent.com/assets/3974120/21993051/3339b47e-dc19-11e6-80bd-99c9e82a899c.jpg)

![missing_link_cl](https://cloud.githubusercontent.com/assets/3974120/21993124/91d639bc-dc19-11e6-80d8-275998c68445.gif)

**Comment by GawainLynch** [comment]
Hey mate, sorry this took a while to get to … big week.

This is actually a UI/UX thing in core. I've raised it with @bobdenotter in Slack, so we'll close this and track in core.
