### ISSUE TITLE
Question: sitemapping with translations

### ISSUE THREAD

**Issue by peterboorsma** [bolt/Sitemap#27]
Is there a way to generate sitemap urls for websites that are multilingual?

If you use the awesome https://github.com/AnimalDesign/bolt-translate extension and the sitemap extension, it would be nice to have an option to add urls per locale. I.e.
A sitemap addition for https://example.com/nl/bla
A sitemap addition for https://example.com/en/bla
A sitemap addition for https://example.com/de/bla

**Comment by HerveEmagma** [comment]
I've fixed it : https://github.com/bolt/Sitemap/pull/33
:)

**Comment by bobdenotter** [comment]
Closed by #33
