### ISSUE TITLE
Small petite tiny docs issue: adding sitemap to <head>

### ISSUE THREAD

**Issue by peterboorsma** [bolt/Sitemap#28]
The sitemap docs advice to add 
<link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml" />
to the head section of your site. 

But the extension takes care of this automatically by adding the line of code itself.

![screen shot 2017-04-26 at 09 19 58](https://cloud.githubusercontent.com/assets/2750653/25422671/f2e5a490-2a61-11e7-95d8-a273a2f6104d.png)

**Comment by bobdenotter** [comment]
Thanks, fixed! 👍
