### ISSUE TITLE
Wrong url when using translations extension

### ISSUE THREAD

**Issue by peterboorsma** [bolt/Sitemap#32]
Sitemap places a link to the location of sitemap.xml in the <head> of the page automatically.
This gives a wrong url when used in combination with the Translate extension

The standard code placed by the Sitemap extension:
`<link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml" />`

The output when used in combination with Translate extension:
`<link rel="sitemap" type="application/xml" title="Sitemap" href="http://my.site/nlsitemap.xml">`

**Comment by HerveEmagma** [comment]
Fixed !
https://github.com/bolt/Sitemap/pull/33/commits/c329933bab95e39545de8d56b4628b461bb2333e

**Comment by bobdenotter** [comment]
Closed by #33
