### ISSUE TITLE
[Question/Bug] HTTP being used on HTTPS page when creating link to Sitemap

### ISSUE THREAD

**Issue by lswest** [bolt/Sitemap#39]
I've just started using this plugin on a website that I'm attempted to put live. On the live system, the website is running over HTTPS (and most links work fine). However, the canonical link from Bolt and the created link for the sitemap from this plugin both use http:// for the link. Not a huge hardship, as they will be redirected. However, I'm wondering where this plugin pulls the domain from, and if I'm missing a configuration step somewhere.

Thanks in advance for any insights you may have!

**Comment by bobdenotter** [comment]
Hi, 

If you clear the cache, and access the bolt backend over HTTPS, bolt ought to update the canonical, as well as the links to the sitemap. 
However, i like to be explicit, and specify it myself in the global `config.yml`: `canonical: https://www.example.org`. This way you surely prevent http <-> http quirks, as well as specifying "yes www" or "no www".

**Comment by lswest** [comment]
Thanks so much for the prompt reply. I'm pretty certain I had previously cleared the cache and logged in via HTTPS. However, specifying it in the config.yml file has fixed it. I hadn't even considered that, since the comment in the file specifically says to not include the protocol. Perhaps it's time to update the comment or the docs?
