### ISSUE TITLE
Warning: in_array() expects parameter 2 to be array, null given in >>/bolt/sitemap/Extension.php on line 61

### ISSUE THREAD

**Issue by cathelijne** [bolt/Sitemap#4]
Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61

Warning: in_array() expects parameter 2 to be array, null given in /home/lijn/vhosts/hikingmom.eu/extensions/vendor/bolt/sitemap/Extension.php on line 61
http://www.hikingmom.eu/ http://www.hikingmom.eu/entries http://www.hikingmom.eu/entry/finding-a-hike-wandelzoekpagina 2015-02-02T16:00:49+00:00 http://www.hikingmom.eu/entry/geocaching 2015-01-31T13:22:43+00:00 http://www.hikingmom.eu/entry/dutch-dunes-meijendel 2015-01-26T16:11:41+00:00 http://www.hikingmom.eu/entry/howto-download-a-map-for-offline-use-with-locus-map-for-android 2015-01-23T12:08:51+00:00 http://www.hikingmom.eu/entry/quechua-forclaz-900-softshell-jacket-for-kids 2015-01-22T14:11:26+00:00 http://www.hikingmom.eu/entry/how-to-make-hiking-with-kids-fun 2015-01-21T15:06:07+00:00 http://www.hikingmom.eu/entry/hi-im-a-mom-and-i-like-to-hike 2015-01-21T09:12:36+00:00 http://www.hikingmom.eu/page/privacy 2015-01-21T22:05:55+00:00 http://www.hikingmom.eu/page/about 2015-01-21T14:07:08+00:00

**Comment by cathelijne** [comment]
Both in HEAD as in 1.0

**Comment by cathelijne** [comment]
This happens when you don't have ANYTHING in the ignore: section of your config. Adding a random (nonexistent) entry there makes it all work, and is a good workaround.

**Comment by xiaohutai** [comment]
Thanks for the info!
I just made a pull request #8 for this.
